### ISSUE TITLE
Please fix the redirectional portal using mobile.

### ISSUE THREAD

**Issue by anonymousseafarer** [bl4nkDEV/SocialX#2]
Maybe the ip conflict. Instead of 192.168.4.1 it should 8.8.8.8 so that any kind of device will automatically redirect the portal.

**Comment by bl4nkDEV** [comment]
I think I fixed it. I am going to try it out and after that if it will work I'll upload it.

**Comment by anonymousseafarer** [comment]
Hope it will work. I will also try it when you upload it. Thank you.

**Comment by bl4nkDEV** [comment]
I have a question. What brand of a mobile device are you using ?

**Comment by anonymousseafarer** [comment]
I'm using iphone 7 plus & samsung s8 plus.

**Comment by bl4nkDEV** [comment]
Okay thanks. I'm going to try fix it as soon as possible.

**Comment by anonymousseafarer** [comment]
![Screenshot_20210912-200159_ArduinoDroid](https://user-images.githubusercontent.com/88724145/132986797-0ec94457-dfbd-41ad-beb5-eefd0e82722d.jpg)
 I try to edit the file of esp8266 phishing.. same problem with socialx but when i use the local ip to 8.8.8.8 and the gateway 8.8.8.8 the portal will redirect to any mobile phone..

**Comment by bl4nkDEV** [comment]
I changed IP but it still doesn't work on my friends IPhone. If you want I can publish the version with changable IP.

**Comment by bl4nkDEV** [comment]
You can try it out: [SocialX_ESP32.zip](https://github.com/bl4nkDEV/SocialX/files/7149773/SocialX_ESP32.zip)

**Comment by bl4nkDEV** [comment]
Added ability to change IP of the ESP. Captive portal is now working properly. At least on my device.
